name: my-first-workflow
# To get a trigger on every push in this repo in any branch
on:
  push:
    branches:
      - dev
      - 'feature-*'
      - main
  pull_request:
    branches:
      - main
env:
  ENV_TYPE: DEV
  APP_USER: thinknyx
  APP_PORT: 80
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps: 
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Step-2 - Checkout
        uses: actions/checkout@v5.0.0
      - name: Step-3
        run: |
          echo `pwd` >> myartifact.txt
          mkdir artifacts
          echo `ls -ltr` >> artifacts/list.txt
          echo `hostname` >> artifacts/hostname.txt
      - name: Upload Single file
        uses: actions/upload-artifact@v5.0.0
        with:
          name: single_file
          path: ./myartifact.txt
  job2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest
    steps: 
      - name: checking current directory
        run: | 
          pwd
          ls -ltr
      - name: Download single file artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: single_file
      - name: checking current directory post download
        run: | 
          pwd
          ls -ltr
          echo "[INFO] Running Deployment for $ENV_NAME."
          echo "[INFO] Application USER will be $APP_USER."
          echo "[INFO] Application will be accessible on $APP_PORT."
          echo "[INFO] Application password is ${{ secrets.APP_PASSWORD }}."
