name: my-first-workflow
# To get a trigger on every push in this repo in any branch
on:
  push:

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps: 
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Step-2 - Checkout
        uses: actions/checkout@v5.0.0
      - name: Step-3
        run: |
          echo `pwd` >> myartifact.txt
          mkdir artifacts/
          echo `ls -ltr` >> artifacts/list.txt
          echo `hostname` >> artifacts/hostname.txt
          echo [READING FILE]
          cat myartifact.txt
      - name: upload artifact - Single file
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: myartifacts
          path: myartifact.txt
      - name: upload artifact - directory
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: directory_artifacts
          path: artifacts/
      - name: upload artifact - multiple paths
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: multiple_paths
          path: |
            artifacts/
            myartifact.txt
      - name: upload artifact - multiple paths with exclusions
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: multiple_paths_with_exclusions
          path: |
            artifacts/
            myartifact.txt
            !**/hostname.txt
          

          
