name: my-first-workflow
# To get a trigger on every push in this repo in any branch
on:
  push:

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps: 
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: Step-2 - Checkout
        uses: actions/checkout@v5.0.0
      - name: Step-3
        run: |
          echo `pwd` >> myartifact.txt
          echo `ls -ltr` >> myartifact.txt
          echo `hostname` >> myartifact.txt
          echo [READING FILE]
          cat myartifact.txt
      - name: upload artifact
        uses: actions/upload-artifact@v5.0.0
        with: 
          name: myartifacts
          path: myartifact.txt
          
